firsts = {
    'Program': ['eof', 'int', 'void'],
    'DL': ['int', 'void'],
    'DL1': ['int', 'void'],
    'Dec': ['int', 'void'],
    'FTS2': ['eps'],
    'FTS': ['eps'],
    'FID1': [';', '['],
    'Params': ['void', 'int'],
    'FVoid': ['eps'],
    'PL1': [','],
    'Param': ['int', 'void'],
    'FTS1': ['eps'],
    'FID2': ['['],
    'CompStmt': ['{'],
    'SL': ['continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', 'minus', '('],
    'SL1': ['continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', 'minus', '('],
    'Stmt': ['continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', 'minus', '('],
    'ExpStmt': ['continue', 'break', '+', 'minus', '('],
    'SelStmt': ['if'],
    'IterStmt': ['while'],
    'RetStmt': ['return'],
    'Fret': [';', '+', '-', '('],
    'SwitchStmt': ['switch'],
    'CaseStmts': ['case'],
    'CaseStmts_1': ['case'],
    'CaseStmt': ['case'],
    'DefaultStmt': ['default'],
    'Expr': ['+', 'minus', '('],
    'Var': ['eps'],
    'FID': ['['],
    'SimpleExpr': ['+', 'minus', '('],
    'FAdditiveExpr': ['<', '=='],
    'Relop': ['<', '=='],
    'AdditiveExpr': ['+', 'minus', '('],
    'AdditiveExpr_1': ['+', 'minus'],
    'Addop': ['+', 'minus'],
    'Term': ['+', 'minus', '('],
    'Term_1': ['*'],
    'SignedFactor': ['+', 'minus', '('],
    'Factor': ['('],
    'Call': ['eps'],
    'Args': ['+', 'minus', '('],
    'ArgList': ['+', 'minus', '('],
    'ArgList_1': [','],
    'ID': ['eps'],
    'Num': ['eps']
}

follows = {
    'Program': ['eps'],
    'DL1': ['eof', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'DL': ['eof', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'Dec': ['int', 'void', 'eof', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'FTS2': ['int', 'void', 'eof', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'FTS': ['int', 'void', 'eof', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'FID1': ['int', 'void', 'eof', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'Params': [')'],
    'FVoid': [')'],
    'PL1': [')'],
    'Param': [')', ','],
    'FTS1': [')', ','],
    'FID2': [')', ','],
    'CompStmt': ['case', 'default', 'else','int', 'void', 'eof', 'continue', 'break', ';', '{',
                 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'SL': ['case', 'default', '}']
    'SL1': ['case', 'default', '}'],
    'Stmt': ['case', 'default', 'else','int', 'void', 'eof', 'continue', 'break', ';', '{',
                'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'ExpStmt': ['case', 'default', 'else','int', 'void', 'eof', 'continue', 'break', ';', '{',
                'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'SelStmt': ['case', 'default', 'else','int', 'void', 'eof', 'continue', 'break', ';', '{',
                'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'IterStmt': ['case', 'default', 'else','int', 'void', 'eof', 'continue', 'break', ';', '{',
                 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'RetStmt': ['case', 'default', 'else','int', 'void', 'eof', 'continue', 'break', ';', '{',
                'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'Fret': ['case', 'default', 'else','int', 'void', 'eof', 'continue', 'break', ';', '{',
             'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'SwitchStmt': ['case', 'default', 'else','int', 'void', 'eof', 'continue', 'break', ';', '{',
                   'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'CaseStmts': ['default', '}'],
    'CaseStmts_1': ['default', '}'],
    'CaseStmt': ['case', 'default', '}'],
    'DefaultStmt': ['}'],
    'Expr': [';', ']', ')', ','],
    'Var': ['*', '+', '-', '<', '==', '=', ';', ']', ')', ','],
    'FID': ['*', '+', '-', '<', '==', '=', ';', ']', ')', ','],
    'SimpleExpr': [';', ']', ')', ','],
    'FAdditiveExpr': [';', ']', ')', ','],
    'Relop': ['+', '-', '('],
    'AdditiveExpr': ['less', 'deq', ';', ']', ')', ','],
    'AdditiveExpr_1': ['less', 'deq', ';', ']', ')', ','],
    'Addop': ['+', '-', '('],
    'Term': ['+', '-', '<', '==', ';', ']', ')', ','],
    'Term_1': ['+', '-', '<', '==', ';', ']', ')', ','],
    'SignedFactor': ['*', '+', '-', '<', '==', ';', ']', ')', ','],
    'Factor': ['*', '+', '-', '<', '==', ';', ']', ')', ','],
    'Call': ['*', '+', '-', '<', '==', ';', ']', ')', ','],
    'Args': [')'],
    'ArgList': [')'],
    'ArgList_1': [')'],
    'ID': ['*', '+', '-', '<', '==', '=', ';', ']', ')', ',', ';', '[', '('],
    'Num': ['*', '+', '-', '<', '==', ';', ']', ')', ',']
}


nullables = ['DL1', 'FVoid', 'PL1', 'FID2', 'DL', 'SL1', 'CaseStmts', 'CaseStmts_1', 'DefaultStmt',
             'SL', 'FID', 'FAdditiveExpr', 'AdditiveExpr_1', 'Term_1', 'Args', 'ArgList_1']