firsts = {
    'Program': ['EOF', 'int', 'void'],
    'DL': ['int', 'void'],
    'DL1': ['int', 'void'],
    'Dec': ['int', 'void'],
    'FTS2': ['id'],
    'VarDec': ['int', 'void'],
    'FTS': ['id'],
    'FID1': [';', '['],
    'TS': ['int', 'void'],
    'FDec': ['int', 'void'],
    'Params': ['void', 'int'],
    'FVoid': ['id'],
    'PL': ['int', 'void'],
    'PL1': [','],
    'Param': ['int', 'void'],
    'FTS1': ['id'],
    'FID2': ['['],
    'CompStmt': ['{'],
    'SL': ['num', 'id', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', 'minus', '('],
    'SL1': ['num', 'id', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', 'minus', '('],
    'Stmt': ['num', 'id', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', 'minus', '('],
    'ExpStmt': ['num', 'id', 'continue', 'break', '+', 'minus', '('],
    'SelStmt': ['if'],
    'IterStmt': ['while'],
    'RetStmt': ['return'],
    'Fret': ['num', 'id', ';', '+', '-', '('],
    'SwitchStmt': ['switch'],
    'CaseStmts': ['case'],
    'CaseStmts_1': ['case'],
    'CaseStmt': ['case'],
    'DefaultStmt': ['default'],
    'Expr': ['num', 'id', '+', 'minus', '('],
    'Var': ['id'],
    'FID': ['['],
    'SimpleExpr': ['num', 'id', '+', 'minus', '('],
    'FAdditiveExpr': ['<', '=='],
    'Relop': ['<', '=='],
    'AdditiveExpr': ['num', 'id', '+', 'minus', '('],
    'AdditiveExpr_1': ['+', 'minus'],
    'Addop': ['+', 'minus'],
    'Term': ['num', 'id', '+', 'minus', '('],
    'Term_1': ['*'],
    'SignedFactor': ['num', 'id', '+', 'minus', '('],
    'Factor': ['num', 'id', '('],
    'Call': ['id'],
    'Args': ['num', 'id', '+', 'minus', '('],
    'ArgList': ['num', 'id', '+', 'minus', '('],
    'ArgList_1': [','],
    'ID': ['id'],
    'Num': ['num']
}


follows = {
    'Program': ['eps'],
    'DL1': ['num', 'id', 'EOF', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'DL': ['num', 'EOF', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'Dec': ['num', 'id', 'int', 'void', 'EOF', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'FTS2': ['num', 'id', 'int', 'void', 'EOF', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'VarDec': ['eps'],
    'FTS': ['num', 'id', 'int', 'void', 'EOF', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'FID1': ['id', 'int', 'void', 'EOF', 'continue', 'break', ';', '{', 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'TS': ['id'],
    'FDec': ['eps'],
    'Params': ['num', ')'],
    'FVoid': [')'],
    'PL': ['eps'],
    'PL1': [')'],
    'Param': [')', ','],
    'FTS1': [')', ','],
    'FID2': [')', ','],
    'CompStmt': ['num', 'id', 'case', 'default', 'else','int', 'void', 'EOF', 'continue', 'break', ';', '{',
                 'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'SL': ['case', 'default', '}'],
    'SL1': ['case', 'default', '}'],
    'Stmt': ['num', 'case', 'default', 'else','int', 'void', 'EOF', 'continue', 'break', ';', '{',
                'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'ExpStmt': ['num', 'id', 'case', 'default', 'else','int', 'void', 'EOF', 'continue', 'break', ';', '{',
                'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'SelStmt': ['num', 'id', 'case', 'default', 'else','int', 'void', 'EOF', 'continue', 'break', ';', '{',
                'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'IterStmt': ['num', 'id', 'case', 'default', 'else','int', 'void', 'EOF', 'continue', 'break', ';', '{',
                'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'RetStmt': ['num', 'id', 'case', 'default', 'else','int', 'void', 'EOF', 'continue', 'break', ';', '{',
                'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'Fret': ['num', 'id', 'case', 'default', 'else','int', 'void', 'EOF', 'continue', 'break', ';', '{',
             'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'SwitchStmt': ['num', 'id', 'case', 'default', 'else','int', 'void', 'EOF', 'continue', 'break', ';', '{',
                   'if', 'while', 'return', 'switch', '+', '-', '(', '}'],
    'CaseStmts': ['default', '}'],
    'CaseStmts_1': ['default', '}'],
    'CaseStmt': ['case', 'default', '}'],
    'DefaultStmt': ['}'],
    'Expr': [';', ']', ')', ','],
    'Var': ['*', '+', '-', '<', '==', '=', ';', ']', ')', ','],
    'FID': ['*', '+', '-', '<', '==', '=', ';', ']', ')', ','],
    'SimpleExpr': [';', ']', ')', ','],
    'FAdditiveExpr': [';', ']', ')', ','],
    'Relop': ['num', '+', '-', '(', 'id'],
    'AdditiveExpr': ['less', 'deq', ';', ']', ')', ','],
    'AdditiveExpr_1': ['less', 'deq', ';', ']', ')', ','],
    'Addop': ['num', 'id', '+', '-', '('],
    'Term': ['+', '-', '<', '==', ';', ']', ')', ','],
    'Term_1': ['+', '-', '<', '==', ';', ']', ')', ','],
    'SignedFactor': ['*', '+', '-', '<', '==', ';', ']', ')', ','],
    'Factor': ['*', '+', '-', '<', '==', ';', ']', ')', ','],
    'Call': ['*', '+', '-', '<', '==', ';', ']', ')', ','],
    'Args': [')'],
    'ArgList': [')'],
    'ArgList_1': [')'],
    'ID': ['*', '+', '-', '<', '==', '=', ';', ']', ')', ',', ';', '[', '('],
    'Num': ['*', '+', '-', '<', '==', ';', ']', ')', ',']
}

nullables = ['DL1', 'FVoid', 'PL1', 'FID2', 'DL', 'SL1', 'CaseStmts', 'CaseStmts_1', 'DefaultStmt',
             'SL', 'FID', 'FAdditiveExpr', 'AdditiveExpr_1', 'Term_1', 'Args', 'ArgList_1']

error_messages = {
    'Program': 'Give a correct program.',
    'DL': 'Decleration is not correct.',
    'DL1': 'Decleration is not correct.',
    'Dec': 'Decleration is not correct.',
    'FTS2': 'Type specification is not correct.',
    'FTS': 'Type specification is not correct.',
    'FID1': 'Type specification is not correct.',
    'Params': 'Parameter specification is not correct.',
    'FVoid': 'Void is not used correct.',
    'PL1': 'Parameter list specification is not correct.',
    'Param': 'Parameter specification is not correct.',
    'FTS1': 'Type specification is not correct.',
    'FID2': 'ID is not correct.',
    'CompStmt': 'Statement specification is not correct.',
    'SL': 'Statement specification is not correct.',
    'SL1': 'Statement specification is not correct.',
    'Stmt': 'Statement specification is not correct.',
    'ExpStmt': 'Expression specification is not correct.',
    'SelStmt': 'Statement specification is not correct.',
    'IterStmt': 'Statement specification for loop is not correct.',
    'RetStmt': 'Statement specification for return is not correct.',
    'Fret': 'Statement specification for return is not correct.',
    'SwitchStmt': 'Statement specification for switch is not correct.',
    'CaseStmts': 'Statement specification for case is not correct.',
    'CaseStmts_1': 'Statement specification for case is not correct.',
    'CaseStmt': 'Statement specification for case is not correct.',
    'DefaultStmt': 'Statement specification for default is not correct.',
    'Expr': 'Statement specification for expression is not correct.',
    'Var': 'Variable usage is not correct.',
    'FID': 'ID specification is not correct.',
    'SimpleExpr': 'Expression is not correct.',
    'FAdditiveExpr': 'Expression is not correct.',
    'Relop': 'Expression is not correct.',
    'AdditiveExpr': 'Algebraic expression is not correct.',
    'AdditiveExpr_1': 'Algebraic expression is not correct.',
    'Addop': 'Algebraic expression for sum and minus is not correct.',
    'Term': 'Algebraic expression for sum and minus is not correct.',
    'Term_1': 'Algebraic expression for product is not correct.',
    'SignedFactor': 'Algebraic expression for is not correct.',
    'Factor': 'Algebraic expression is not correct.',
    'Call': 'Calling is not correct.',
    'Args': 'Argument expression is not correct.',
    'ArgList': 'Argument expression is not correct.',
    'ArgList_1': 'Argument expression is not correct.',
    'ID': 'ID expression is not correct.',
    'Num': 'Number expression is not correct.'
}